import { FONT_PRETENDARD } from "@/lib/font-util";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "한국지방교육행정연구재단",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={FONT_PRETENDARD.className}>{children}</body>
    </html>
  );
}
