import { FONT_PRETENDARD } from "@/lib/font-util";
import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/main/navbar";
import Footer from "@/components/main/Footer";

export const metadata: Metadata = {
  title: "한국지방교육행정연구재단",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={FONT_PRETENDARD.className}>
        <main className="w-full flex flex-col relative">
          <NavBar />

          {children}

          <Footer />
        </main>
      </body>
    </html>
  );
}
